[project]
name = "snpxarray"
version = "0.1.0"
description = "Convert PySnpTools BED files to xarray DataArrays"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["xarray>=2023.1.0", "pysnptools>=0.5.0", "numpy>=1.20.0"]

[project.optional-dependencies]
dev = ["jupyter", "matplotlib", "seaborn"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = ["jupyter>=1.0.0", "matplotlib>=3.5.0", "seaborn>=0.11.0"]
