[project]
name = "snpxarray"
version = "0.1.0"
description = "Convert PySnpTools BED files to xarray DataArrays"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "xarray>=2025.7.1",
    "pysnptools>=0.5.14",
    "numpy>=2.3.1",
    "zarr>=3.0.10",
]

[project.optional-dependencies]
dev = ["jupyter", "matplotlib", "seaborn"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = ["snpxarray.ipynb", "README.md"]

[tool.uv]
dev-dependencies = ["jupyter>=1.0.0", "matplotlib>=3.5.0", "seaborn>=0.11.0"]
